<a href="https://colab.research.google.com/github/SAGARNATH-S/front-end-web-development/blob/master/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5]
print(l)

[1, 2, 3, 4, 5]


Converting List into 1D array

In [3]:
ar=np.array(l)
print(ar)

[1 2 3 4 5]


Creating list of list and converting into 2D array

In [5]:
m=[[1,2,3],[3,4,5],[5,6,7]]
n=np.array(m)
print("list of list",m,"\n")
print(n,"2D array")

list of list [[1, 2, 3], [3, 4, 5], [5, 6, 7]] 

[[1 2 3]
 [3 4 5]
 [5 6 7]] 2D array
